-- Citation-graph tables on ny_caselaw.
--
-- Originally lived in the `collections` app DB. Moved here as part of the
-- D5-partial slice (2026-05-26) so the citation pipeline becomes self-
-- contained on the merged DB — no cross-DB join required for the cited_by
-- query, and the pipeline scripts need only MERGE_TARGET_URL configured.
--
-- Foreign keys to `sources(reference)` are intentionally dropped here
-- (the collections version had them). source_ref validity is already
-- enforced via the cases.source_ref CHECK constraint elsewhere in this
-- DB, and the sources registry table itself doesn't live in ny_caselaw.

CREATE TABLE IF NOT EXISTS public.extracted_citations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    citing_source_ref text NOT NULL,
    raw_citation_text text NOT NULL,
    case_name text,
    cited_volume integer NOT NULL,
    cited_reporter text NOT NULL,
    cited_reporter_norm text NOT NULL,
    cited_first_page integer NOT NULL,
    status text DEFAULT 'unresolved'::text NOT NULL,
    resolved_source_ref text,
    error_reason text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    cited_name_text text,
    external_curie text,
    case_curie text,
    citing_case_curie text,
    resolved_case_curie text,
    CONSTRAINT extracted_citations_status_chk
      CHECK (status = ANY (ARRAY['unresolved'::text, 'resolved'::text, 'ambiguous'::text, 'invalid'::text, 'likely'::text]))
);

CREATE INDEX IF NOT EXISTS idx_extracted_citations_status
  ON public.extracted_citations (status);
CREATE INDEX IF NOT EXISTS idx_extracted_citations_triplet
  ON public.extracted_citations (cited_reporter_norm, cited_volume, cited_first_page);
CREATE INDEX IF NOT EXISTS idx_extracted_citations_case_curie
  ON public.extracted_citations (case_curie) WHERE case_curie IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_extracted_citations_citing_case_curie
  ON public.extracted_citations (citing_case_curie) WHERE citing_case_curie IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_extracted_citations_citing_curie
  ON public.extracted_citations (citing_source_ref, citing_case_curie) WHERE citing_case_curie IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_extracted_citations_resolved_case_curie
  ON public.extracted_citations (resolved_case_curie) WHERE resolved_case_curie IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_extracted_citations_resolved_curie
  ON public.extracted_citations (resolved_source_ref, resolved_case_curie) WHERE resolved_case_curie IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_extracted_citations_unique_curie
  ON public.extracted_citations (citing_source_ref, citing_case_curie, cited_reporter_norm, cited_volume, cited_first_page)
  WHERE citing_case_curie IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.case_citation_counts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ref text NOT NULL,
    cited_case_name_norm text,
    cited_case_norm text,
    citing_case_count integer NOT NULL,
    last_computed_at timestamp without time zone DEFAULT now() NOT NULL,
    cited_case_curie text
);

CREATE INDEX IF NOT EXISTS idx_case_citation_counts_case
  ON public.case_citation_counts (source_ref, cited_case_curie);
CREATE INDEX IF NOT EXISTS idx_case_citation_counts_cited_case_curie
  ON public.case_citation_counts (cited_case_curie) WHERE cited_case_curie IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_case_citation_counts_source_ref_count
  ON public.case_citation_counts (source_ref, citing_case_count DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_case_citation_counts_source_curie
  ON public.case_citation_counts (source_ref, cited_case_curie) WHERE cited_case_curie IS NOT NULL;

-- Grant read access to the local `claude` user (DDL-less read role).
-- The dev/staging Postgres roles for these envs may differ; harmless if missing.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'claude') THEN
    EXECUTE 'GRANT SELECT ON TABLE public.extracted_citations TO claude';
    EXECUTE 'GRANT SELECT ON TABLE public.case_citation_counts TO claude';
  END IF;
END$$;
