-- Migration: Replace opinion_overruled_cases with broader opinion_negative_treatments
-- Two-tier classification: hard_negative (overruled, reversed) and advisory
-- (declined_to_follow, distinguished, criticized, limited).
--
-- No backfill — pre-product-validation phase, data will be regenerated by re-analysis.

DROP TABLE IF EXISTS opinion_overruled_cases CASCADE;

CREATE TABLE IF NOT EXISTS opinion_negative_treatments (
  id SERIAL PRIMARY KEY,
  opinion_id INTEGER NOT NULL REFERENCES opinions(id) ON DELETE CASCADE,
  tier TEXT NOT NULL CHECK (tier IN ('hard_negative','advisory')),
  type TEXT NOT NULL CHECK (type IN (
    'overruled','reversed','declined_to_follow','distinguished','criticized','limited'
  )),
  case_name TEXT,
  citation TEXT,
  basis TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT chk_ont_tier_type CHECK (
    (tier = 'hard_negative' AND type IN ('overruled','reversed'))
    OR
    (tier = 'advisory' AND type IN ('declined_to_follow','distinguished','criticized','limited'))
  )
);

CREATE INDEX IF NOT EXISTS idx_ont_opinion_id ON opinion_negative_treatments (opinion_id);
CREATE INDEX IF NOT EXISTS idx_ont_tier       ON opinion_negative_treatments (tier);
CREATE INDEX IF NOT EXISTS idx_ont_type       ON opinion_negative_treatments (type);

-- Dedup unique index (uses COALESCE so NULL case_name/citation still collapse sensibly).
CREATE UNIQUE INDEX IF NOT EXISTS uniq_ont_dedup
  ON opinion_negative_treatments (
    opinion_id, tier, type,
    COALESCE(case_name, ''),
    COALESCE(citation, ''),
    basis
  );

-- Trigram indexes for fuzzy search (pg_trgm assumed enabled by prior migrations).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'idx_ont_case_name_trgm' AND n.nspname = 'public'
  ) THEN
    EXECUTE 'CREATE INDEX idx_ont_case_name_trgm ON opinion_negative_treatments USING gin (case_name gin_trgm_ops)';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'idx_ont_citation_trgm' AND n.nspname = 'public'
  ) THEN
    EXECUTE 'CREATE INDEX idx_ont_citation_trgm ON opinion_negative_treatments USING gin (citation gin_trgm_ops)';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'idx_ont_basis_trgm' AND n.nspname = 'public'
  ) THEN
    EXECUTE 'CREATE INDEX idx_ont_basis_trgm ON opinion_negative_treatments USING gin (basis gin_trgm_ops)';
  END IF;
END
$$;

-- Rename batch tracking column to match new terminology.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='batch_opinion_requests' AND column_name='overruled_cases_extracted'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='batch_opinion_requests' AND column_name='negative_treatments_extracted'
  ) THEN
    ALTER TABLE batch_opinion_requests RENAME COLUMN overruled_cases_extracted TO negative_treatments_extracted;
  END IF;
END
$$;
