-- Migration: Add stable CURIE columns to cases and opinions.
--
-- Motivation: analysis tables (opinion_holdings, opinion_negative_treatments,
-- opinion_keywords, opinion_citations) currently FK on opinions.id, which is
-- a local SERIAL PK and drifts across reimports. To make analysis survive a
-- full reimport of the case corpus, we introduce text CURIEs that are
-- deterministic from the source data:
--
--   cases.curie   — reporter:volume:page[:rhs-name]
--                   (generated by generateCaseCurie() in
--                    co-collection/src/utils/curieGeneration.js)
--
--   opinions.curie — <caseCurie>#<index>-<type>[-<author-slug>]
--                    (generated by generateOpinionCurie() in the same file;
--                     `index` is the zero-based position within CAP's opinions
--                     array for the parent case)
--
-- opinions.opinion_index is added so the positional anchor is stored
-- explicitly, rather than recovered from `opinions.id ASC`. The importer
-- must populate this during case ingest.
--
-- Columns are added as nullable. A separate backfill script populates them
-- for existing rows; once backfill completes and the importer is wired to
-- emit them for new inserts, a follow-up migration will add NOT NULL.
--
-- This migration does NOT alter any analysis table FKs. That cut-over
-- happens in a later migration, once every opinion in every enabled source
-- has a non-null CURIE.

-- 1) cases.curie
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'cases' AND column_name = 'curie'
  ) THEN
    ALTER TABLE cases ADD COLUMN curie TEXT;
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uniq_cases_curie ON cases (curie)
  WHERE curie IS NOT NULL;

-- 2) opinions.curie + opinions.opinion_index
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'opinions' AND column_name = 'curie'
  ) THEN
    ALTER TABLE opinions ADD COLUMN curie TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'opinions' AND column_name = 'opinion_index'
  ) THEN
    ALTER TABLE opinions ADD COLUMN opinion_index INTEGER;
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uniq_opinions_curie ON opinions (curie)
  WHERE curie IS NOT NULL;

-- Enforce that (case_id, opinion_index) is unique when both are present —
-- catches importer bugs that would otherwise double-insert the same slot.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_opinions_case_index
  ON opinions (case_id, opinion_index)
  WHERE opinion_index IS NOT NULL;
